services:
  # --- Backend Application ---
  app:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    container_name: world_play_app_backend
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/packages/server/node_modules
      - /usr/src/app/packages/shared/node_modules # הוספנו את זה
    depends_on:
      - db
      - media-server

  # --- Media Server (WebRTC + FFmpeg) ---
  media-server:
    build:
      context: ./packages/media-server
      dockerfile: Dockerfile
    container_name: world_play_media_server
    ports:
      - "8000:8000"
      - "10000-10100:10000-10100/udp"
    volumes:
      - ./packages/media-server/temp:/tmp/media

  # --- DB ---
  db:
    image: postgres:15-alpine
    container_name: world_play_app_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: